build_script:  
  - ps: ./build.ps1 -Target Build

test_script:
  - ps: ./build.ps1 -Target Test
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
